---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: <%= ENV['CHEF_VERSION'] || 'latest' %>
  install_strategy: <%= ENV['CHEF_INSTALL'] || 'once' %>
  log_level: <%= ENV['CHEF_LOG_LEVEL'] || 'auto' %>

verifier:
  name: inspec

platforms:
  - name: windows-2012r2
  - name: windows-2016

suites:
  - name: default
    run_list:
      - recipe[pspki::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
