---
driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  username: <%= ENV["winrm_user"] %>
  password: <%= ENV["winrm_pass"] %>
  port: <%= ENV["winrm_port"] %>

provisioner:
  name: chef_zero
  product_name: chef
  product_version: <%= ENV['CHEF_VERSION'] || 'latest' %>
  install_strategy: <%= ENV['CHEF_INSTALL'] || 'once' %>
  log_level: <%= ENV['CHEF_LOG_LEVEL'] || "auto" %>

verifier:
  name: inspec

platforms:
  - name: windows

suites:
  - name: default
    run_list:
      - recipe[pspki::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
